[project]
name = 'Quantum-Classical-Hybrid-Cryptography-Standards-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.algorithm-submission]
path = 'contracts/algorithm-submission.clar'
clarity_version = 2
epoch = 2.5

[contracts.certified-algorithm-nft]
path = 'contracts/certified-algorithm-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.collaborative-research]
path = 'contracts/collaborative-research.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
